#NOME APLICACAO.
spring:
  application:
    name: eleitorado-sever
  http:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/eleitorado
    username: postgres
  jpa:
    generate-ddl: true

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 9090
  compression:
    enabled: true
    mime-types: image/png, image/jpeg, text/html, text/xml, text/plain, text/css, application/javascript, application/json

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddres: true